# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d9942abf54fc6197fe6b48d3f7a4e09e573d797463f896b34e288bf984520196e9fd87c8d09825db89c4994289a1508dc3b26f50ce33a9cf8d50e17d01f423d

test:
  secret_key_base: 21faeee3b6f26ee1b1e284ab991e0f44281013bffe5b07bdffc8a6876a25819c75df88262ef62bf37a80914ff9d36e113991d3f4bcd478fbe62f4923ca3b3ef1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
